### ISSUE TITLE
Please don't make filters.txt bigger

### ISSUE THREAD

**Issue by curiosity-seeker** [mmotti/adguard-home-filters#1]
I don't use your filters in AdGuardHome as I went back to Pi-Hole which I like better (and which I'm using with your other scripts).

However, I'm successfully using your `filters.txt` and `regex.txt` in **AdGuard Pro** on my iPhone and iPad. I've added them as [subscriptions](https://kb.adguard.com/en/ios/features#subscriptions) to the "Privacy Settings" which allows for a system-wide blocking on those devices via a local VPN. I seriously think that your lists are simply the best available!

There is just one possible problem: When I added several hosts files in the past I was faced with the problem mentioned on above site:

> NOTE: Important to notice that too many subscriptions can lead to tunnel crash, i.e. the app will stop responding and the filtering will cease.

Fortunately, this does not happen with your lists: They block all sub-domains of those trackers/adservers/etc. but are not that big to cause a tunnel crash.

So my plea is: Don't make filters.txt bigger as it is now as it would probably no longer work in AdGuard Pro. 

If you really plan to add new hosts files I suggest to offer them as separate filterlists for AdGuardHome (where a tunnel crash does not occur). 

Thanks for considering this and thanks for your great work!

**Comment by mmotti** [comment]
I am glad to hear that the filters are working well for you!

I would, however, suggest that the use of proper filters such as EasyList and EasyPrivacy would be more suitable for AdGuard Pro as it can interpret / support a much wider variety of filter options. The filters that have been created for this repo have been 'dummed down' to try to apply basic blocking where the advanced traffic analysis is not available.

I do not plan to add any additional host sources at present, but will consider the possibility of separating them out if necessary in the future. If the AdGuard Home code is tweaked so that more 'options' are processed as wildcard blocks, there will be no reason for this repo to exist. It's really a temporary measure until there's a solution in-place :-)

**Comment by curiosity-seeker** [comment]
Thanks for your answer!

Regarding EasyList and EasyPrivacy: I know that. The thing is that [AdGuard **Pro**](https://adguard.com/en/adguard-ios-pro/overview.html) for iOS consists of 2 parts:
1. There is a blocker for Safari using EasyList etc. Unfortunately, the maximum number of filter rules for a filter engine allowed in Safari is 50,000. That's why the newer [AdGuard for iOS](https://adguard.com/en/adguard-ios/overview.html) (which is a pure Safari blocker) applies 5 filter engines thus increasing the max. number of filter rules to nearly 250,000. Consequently, I disabled all Safari filterlists in AdGuard Pro and use AdGuard instead. 
2. The second part of AdGuard Pro is the "Privacy Settings" which creates a local VPN on the device which alllows to filter the network requests of all other installed apps. Here support of sophisticated options of the ABP filter syntax is irrelevant - rather, it's all about blocking access to those tracking/advertising domains thus preventing being tracked by those apps. I'm only using that second part of AdGuard Pro, and for this purpose your filterlist is much more efficient than any hosts file. 

That's why I sincerely hope that your "temporary measure" will exist for a long time ;-)
